:readme:
:branch: 5.14
:docs: https://neo4j.com/docs/apoc/current
:apoc-release: 5.14.0
:neo4j-version: 5.14.0

= Neo4j APOC light-weight reasoner

This repository is a fork of the original https://github.com/neo4j/apoc[Awesome Procedures for Neo4j^]. It has been extended to support light-weight reasoning in Neo4j only handling events of node and relationship creation.

== Build and installation
You can build the artifact as explained in the https://github.com/neo4j/apoc[Build & install the current development branch from source] section of the official APOC `readme.adoc` file. Then you can move the jar in the Neo4j plugins directory.

== Changes
We extended the implementation of the `before` phase in the `apoc.trigger` module. Changes include the support for triggers dependency and stratification as well as event buffers and selective trigger firing.

WARNING: If your application relies on APOC triggers, especially those utilizing the `before` phase, please note that using this custom implementations might result in altered behavior compared to the original `apoc.trigger` module. This could potentially lead to unexpected errors in the code.

=== Trigger definition syntax

The recent updates necessitate defining triggers using a new syntax. It is now essential to include two additional <key, value> pairs within the `selector` parameter:

- `stratum`: an integer representing the trigger's stratum. This determines the order of trigger activation, with strata being processed in ascending order.
- `event`: a string that specifies either the relationship type or node label for which the trigger awaits creation.

To use the new features, you have to use the `before` phase.

.Trigger definition example
[source,cypher,subs=attributes]
----
CALL apoc.trigger.install("reactive", "RecursivePotDControl",
"UNWIND $createdRelationships AS newRel
MATCH (x:Company)-[newRel:potDControl]->(z:Company),
(z)-[:own]->(y:Company),
(x)-[:control]->(y)
MERGE (x)-[:potDControl]->(y)",
{phase: 'before', stratum: 1, event: 'potDControl'});
----



== Disclaimer

WARNING: The authors and contributors of this repository provide the code and resources "as is," without warranty of any kind, express or implied. The use of this code or any included resources is at your own risk. The authors shall not be liable for any damages or losses arising out of the use or inability to use the code or resources provided in this repository.

